---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - image: shurikk/echo-server
        name: service
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  selector:
    app: echo-server
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
